# Generated by Django 2.0 on 2018-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_trasacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trasacao',
            options={'verbose_name_plural': 'Trasações'},
        ),
        migrations.AlterField(
            model_name='trasacao',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trasacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
