# Generated by Django 2.0 on 2018-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20181203_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
